# Generated by Django 3.2.2 on 2021-05-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='User_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Attendance_System.userinfo'),
            preserve_default=False,
        ),
    ]
