# Generated by Django 3.2.2 on 2021-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0002_records_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default=0, upload_to='static/images/ImagesAttendance'),
            preserve_default=False,
        ),
    ]
