# Generated by Django 3.2.2 on 2021-05-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0004_auto_20210513_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='User_ID',
        ),
    ]
