# Generated by Django 3.2.2 on 2021-05-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0007_remove_records_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='Semester',
            new_name='semester',
        ),
    ]
