# Generated by Django 3.2.2 on 2021-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0008_auto_20210514_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='User',
            new_name='user',
        ),
    ]
