# Generated by Django 3.2.2 on 2021-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0009_auto_20210514_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
