# Generated by Django 3.2.2 on 2021-06-01 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System', '0012_alter_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 9, 59, 59))),
                ('opening_time_max', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 11, 59, 59))),
                ('closing_time', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 9, 59, 59))),
                ('closing_time_max', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 11, 59, 59))),
            ],
        ),
    ]
